### ISSUE TITLE
Question. Choose one license in license groups.

### ISSUE THREAD

**Issue by Niccolum** [FHPythonUtils/LicenseCheck#10]
As I see according 2021.3 changes - we can choose groups of licenses. But what if I want to use one of license in groups, but not others? How to catch this case?

**Comment by FredHappyface** [comment]
How do you mean? Are you meaning that you may want to fail-licenses gpl but not gplv3?

If that's the case then you'd need to supply gplv2 and gplv3+ at present

**Comment by Niccolum** [comment]
I see table here
https://choosealicense.com/appendix/
and imagine case:
What if I want to use BSD Zero Clause License, but no other BSD licenses?

**Comment by FredHappyface** [comment]
Hmm yeah at the moment the lib only supports a subset of the python license classifiers cos that's what is used primarily to identify the license 

But yeah it would have to be done as my example for gpl excluding gplv3 and I think changing that would overcomplicate the CLI interface and would likely lead to an over engineered lib

**Comment by Niccolum** [comment]
Maybe realize that only in config file according https://github.com/FHPythonUtils/LicenseCheck/issues/11 ?)
