### ISSUE TITLE
Feature: Add config file functionality

### ISSUE THREAD

**Issue by Niccolum** [FHPythonUtils/LicenseCheck#11]
I can't find this in docs. Can we write config file (and add path to it, like in flake, pylint, gunicorn or other cli tools instead of flags?

**Comment by FredHappyface** [comment]
Currently no, but this is something I'd like to add 

At the moment I'm thinking of adding a field into pyproject.toml perhaps with a fallback to a dot file 

I shall also add this to my to-do

**Comment by Niccolum** [comment]
it would be awesome if there were both of these options!

**Comment by FredHappyface** [comment]
fixed in 2021.4
