### ISSUE TITLE
Reduce default pool size to 1

### ISSUE THREAD

**Issue by matthewdeanmartin** [FHPythonUtils/LicenseCheck#12]
It looks like this is querying pypi very rapidly by default. Even after I set POOL_SIZE=1, it rapidly exhausts the rate limit and then instead of waiting, it fails.

It looks like license_check itself isn't at fault, but the way that yolk is configured & how it isn't respecting rate limits.

This is on a requirements.txt file of about 20 packages.

`xmlrpc.client.Fault: <Fault -32500: 'HTTPTooManyRequests: The action could not be performed because there were too many requests by the client. Limit may reset in 53 seconds.'>`

**Comment by Niccolum** [comment]
@matthewdeanmartin can you add your requirements.txt file here for testing purposes?

**Comment by FredHappyface** [comment]
I'll take a look at this, though if you can include your reqs.txt that'd be great and then I can scratch my head over this 😁

**Comment by matthewdeanmartin** [comment]
Nothing special about the requirements.txt file -- I was reviewing a variety of license checking tools.

I think the issue has something to do with pypi a while ago blocking all xmlrpc calls because someone in the world was essentially DDOSing those endpoint & if they work again at all, pypi is definitely doing some aggressive rate limiting.

```
$ cat requirements.txt
certifi==2021.5.30
charset-normalizer==2.0.4
cleo==0.8.1
click==7.1.2
clikit==0.6.2
crashtest==0.3.1
Flask==1.1.4
greenlet==1.1.1
idna==3.2
itsdangerous==1.1.0
Jinja2==2.11.3
license-info==0.8.7
licensecheck==2021.3
lilili==0.1.0
MarkupSafe==2.0.1
pastel==0.2.1
pip-licenses==3.5.1
pkgtools==0.7.3
PTable==0.9.2
pylev==1.4.0
PyYAML==5.4.1
requests==2.26.0
requirements-parser==0.2.0
SQLAlchemy==1.4.22
tomlkit==0.7.2
urllib3==1.26.6
Werkzeug==1.0.1
```

**Comment by FredHappyface** [comment]
Can I confirm this is the sort of thing you'd be wanting to do? https://stackoverflow.com/questions/18466079/can-i-change-the-connection-pool-size-for-pythons-requests-module

(Just rather than using 100 using a lower value and perhaps even allowing an end user to configure this?)

**Comment by matthewdeanmartin** [comment]
Oh shoot! I just realized a filed a bug against the wrong repo! I feel dumb now. I checked, there is no way for the endpoint you are using (ref https://warehouse.pypa.io/api-reference/index.html ) since those things are cached on CDNs

I am fighting other bugs while using licensecheck, which I will file separately.
