### ISSUE TITLE
Feature: Support for proprietary license

### ISSUE THREAD

**Issue by takeda** [FHPythonUtils/LicenseCheck#15]
## Feature
- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

### Is your feature request related to a problem? Please describe

Currently when a proprietary license is defined, for example classifiers contains:
`License :: Other/Proprietary License`
The licensecheck results with unhelpful error
```
KeyError: <License.NO_LICENSE: 200
```

### Describe the solution you'd like

Ideally licensecheck should just list licenses used by dependencies and mark licenses blacklisted in configuration.

### Describe alternatives you've considered

As a workaround I can mark my project that it uses MIT license and get the output, but that forces me to provide false information in my project.

**Comment by FredHappyface** [comment]
Just need to add proprietary license so I'll add that to the todo list

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/LicenseCheck/commit/746eace6795c9231772e8a91cc340a6d40a68a2c
