### ISSUE TITLE
Feature: give an option to only list running dependencies

### ISSUE THREAD

**Issue by takeda** [FHPythonUtils/LicenseCheck#16]
## Feature
- [x] I have read the comment above and have completed each step
- [x] I have filled in each heading below

### Is your feature request related to a problem? Please describe

Currently when running licensecheck with poetry, it shows licenses for all dependencies (including development tools).
Most of the time only running dependencies matter since those are integrated with package's code.

### Describe the solution you'd like

Since there might be use cases where someone wants to check all dependencies, consider adding an option where we can exclude dev-dependencies. Not sure what the default should be, I'm fine with either way.

### Describe alternatives you've considered

I found a workaround by simply invoking two commands, but it would be great if that was not necessary:
```shell
poetry export --without-hashes -o requirements.txt
poetry run licensecheck -u requirements
```

**Comment by FredHappyface** [comment]
Taken a look and seems this can be achieved pretty easily: https://python-poetry.org/docs/cli/#options-5 so I'll take a look at this

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/LicenseCheck/commit/0784b2bfc0cb4327d06a1dffb9f135bd22db2c59
