### ISSUE TITLE
Bug: TypeError due to Typing

### ISSUE THREAD

**Issue by GrazingScientist** [FHPythonUtils/LicenseCheck#22]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Linux 5.15.0-52-generic #58~20.04.1-Ubuntu
- Browser: 
- licensecheck Version: 2022.2
- python Version: 3.8

### Describe the bug
After freshly installing the current version of `licensecheck` and typing the command `licensecheck`, I get the following error:

```
Traceback (most recent call last):
  File "/home/me/myproject/venv/bin/licensecheck", line 5, in <module>
    from licensecheck import cli
  File "/home/me/myproject/venv/lib/python3.8/site-packages/licensecheck/__init__.py", line 13, in <module>
    from licensecheck import formatter, get_deps
  File "/home/me/myproject/venv/lib/python3.8/site-packages/licensecheck/formatter.py", line 50, in <module>
    def ansi(packages: list[PackageCompat]) -> str:
TypeError: 'type' object is not subscriptable
```

I know this error occurs, when in Python 3.8, you want to use `list` as type hint, although in 3.8 you still need to use `List`.

### Expected outcome

No error message. :)

**Comment by FredHappyface** [comment]
Thanks for raising this. The bug slipped through as my python env is newer than this 

I have missed 
```
from __future__ import annotations 
```

I'll get a fix out ASAP

**Comment by GrazingScientist** [comment]
If I had knew that it can be solved this way, I would have made a PR. 🙈
