### ISSUE TITLE
Info key not available within Pypi json 

### ISSUE THREAD

**Issue by bnpani** [FHPythonUtils/LicenseCheck#24]
Hi, 

I just noticed this error whenever I run **licensecheck**, or if I use the packageInfoFromPypi function for a list of packages.

I'll attach a picture with the actual error from PyCharm.

![library_error](https://user-images.githubusercontent.com/100778834/208386223-36853f27-3e56-40e1-baeb-5b68b2ccfd9d.jpg)

**Comment by FredHappyface** [comment]
Hey thanks for the issue, works for the python 'requests' lib. Can you send the list of deps please?
