### ISSUE TITLE
Feature: Support for PEP631: Declaring dependencies in pyptoject.toml

### ISSUE THREAD

**Issue by dries007** [FHPythonUtils/LicenseCheck#32]
## Feature

- [X] I have read the comment above and have completed each step
- [X] I have filled in each heading below

### Is your feature request related to a problem? Please describe

I'm using the build system Hatch, without a separate `requirements.txt` file, and I would like to check my dependencies' licences without first having to extract that information with a separate step.

### Describe the solution you'd like

Support is added to directly read dependencies from `pyproject.toml`.

### Describe alternatives you've considered

Continue to use a wrapper script to first create a `requirements.txt` file and then delete it again.

### Additional context

- https://peps.python.org/pep-0631/
- https://hatch.pypa.io/latest/config/dependency/

**Comment by FredHappyface** [comment]
Thanks for this, merged and released :)
