### ISSUE TITLE
Bug: docutils license is not parsed as BSD

### ISSUE THREAD

**Issue by 12rambau** [FHPythonUtils/LicenseCheck#35]
## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info
- [x] I have described the bug, filled in the expected outcome and the actual
outcome including screenshots where appropriate

### System info

- OS: Linux LAPTOP-VQJVCNH4 5.15.90.1-microsoft-standard-WSL2
- Version: 2023.1.1

### Describe the bug

The theme project depends directly on [docutils](https://pypi.org/project/docutils/) (it's the base of every sphinx related stuff) and it raises an incompatibility issue as it's not identified correctly.

### Expected outcome

```
list of packages                                
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Compatible ┃ Package               ┃ License(s)                              ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ ✔          │ docutils              │ BSD License                             │
└────────────┴───────────────────────┴─────────────────────────────────────────┘
```

### Actual outcome

```
list of packages                                
┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Compatible ┃ Package               ┃ License(s)                              ┃
┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ ✖          │ docutils              │ BSD License;; GNU General Public        │
│            │                       │ License (GPL);; Python Software         │
│            │                       │ Foundation License;; Public Domain      │
└────────────┴───────────────────────┴─────────────────────────────────────────┘
```

**Comment by FredHappyface** [comment]
This is intended behaviour as licensecheck may use pypi.org to discover the metadata https://pypi.org/project/docutils/#data or the local package metadata 

The license is 

> License: BSD License, GNU General Public License (GPL), Python Software Foundation License, Public Domain (public domain, Python, 2-Clause BSD, GPL 3 (see COPYING.txt))

Probably best to open this with docutils to get some more clarity on what license they are actually under (may be that pypi.org needs updating)

**Comment by 12rambau** [comment]
I checked the referenced copying.txt: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/COPYING.txt#l146 and it seems they made a very good work at gathering all the licences of the project ence the complex references. Pypi is accepting this structure as well (LicenseA;; Licence B;; ...), so nothing we can do there. 

I opened a ticket on their side but I doubt they will accept to change anything (https://sourceforge.net/p/docutils/bugs/469/) as they embed multiple levels of Licensing. 

Then let's change path, would it be possible to ignore a dependeçy ? 

- user could get rid of poorly set licenses (like docutils) 
- as it's a manual change user will keep control over what is ignored and not (play at your own risk) 

```toml
[tools.licensecheck]
ignore=["docutils"]
```

What would you think ?
