### ISSUE TITLE
Bug: Apache2 is shown as incompatible with LGPL3 (LGPLV3)

### ISSUE THREAD

**Issue by J-Christophe** [FHPythonUtils/LicenseCheck#40]
## Question

- [x] I have read the comment above and have completed each step

My software is under LGPLV3 and I have a few dependencies with Apache License 2.0

When I run licensecheck, the output shows the software under Apache License 2.0 cannot be integrated to a project under LGPLV3.
As far I know, there is no problem : https://en.wikipedia.org/wiki/License_compatibility.

Is it a bug from licensecheck ? Could you provide a document that explains the compatibility between licenses ?

Thanks

**Comment by FredHappyface** [comment]
Hmm yeah might be. I know that GPL2 is not compatible but iirc ths was changed for v3. Perhaps it's identifying your license as GPL. May well need further investigation

**Comment by ftessier** [comment]
I just stumbled on this issue too. Apache v2 code can be included in gpl-3, although not the other way around. Hence `licencecheck` should reflect that: Apache v2 modules included in a gpl-3 project should be marked as `compatible`.

- https://www.gnu.org/licenses/license-list.en.html#apache2
- https://www.apache.org/licenses/GPL-compatibility.html

**Comment by J-Christophe** [comment]
There is also this nice website to check the compatibility of licenses : 
https://joinup.ec.europa.eu/collection/eupl/solution/joinup-licensing-assistant/jla-compatibility-checker

**Comment by FredHappyface** [comment]
Thanks for the updates on this 

So according to current functionality: Apache 2 -> lgpl3 should be considered compatible, whereas Apache 2 -> gpl3 isn't

This is absolutely a bug 

More info on licence compatibility for GPL licenses is at https://gplv3.fsf.org/wiki/index.php/Compatible_licenses and https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses

**Comment by ftessier** [comment]
I believe that `apache-2` _**IS**_ compatible with `gpl-3`. I have not looked into lgpl at all.

**Comment by FredHappyface** [comment]
Yes, talking licenses quickly gets confusing! To clarify 

|License In| license out | current behaviour| desired behaviour| bug in current version?
|---|---|---|---|---
|Apache 2|lgpl3|compatible|compatible|no
|Apache 2|gpl3|incompatible|compatible|yes

**Comment by fhg-isi** [comment]
As a workaround one can use the console command option `--ignore-licenses` to ignore Apache license:

`licensecheck --ignore-licenses 'Apache'`

Unfortunately, that does not seem to work in pyproject.toml and not for multiple licenses: #46

**Comment by FredHappyface** [comment]
fixed in 2023.2
