### ISSUE TITLE
Feature: Improve error message No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by fhg-isi** [FHPythonUtils/LicenseCheck#44]
### Is your feature request related to a problem? Please describe

I got the Error message
`No such file or directory: 'requirements.txt'`
and found it confusing, because I do not have a requiremnts.txt on purpose and use pyproject.toml.

My underlying issue was, that I was not in the right directory ( forgot to `cd back_end`).

You might want to adapt the message to something like 

"Could not find specification of requirements (requirements.txt or pyproject.toml)."

**Comment by FredHappyface** [comment]
Thanks for this, yeah I'll update this to be more helpful on my next dev cycle :)

**Comment by FredHappyface** [comment]
fixed in 2023.2
