### ISSUE TITLE
Bug: Classifier and License Mismatch

### ISSUE THREAD

**Issue by KyleKing** [FHPythonUtils/LicenseCheck#5]
> TLDR: the license `classifier` overrides the `license` which can cause confusion if the values differ

## Bug

- [x] I have read the comment above and have completed each step
- [x] I have filled out the system info {N/A}
- [x] I have described the bug, filled in the expected outcome and the actual outcome including screenshots where appropriate

### Example

```sh
poetry new test_licensecheck
cd test_licensecheck
poetry add licensecheck
```

Manually edit the toml file with a license and classifier as necessary

```toml
[tool.poetry]
license = "MIT License"
classifiers = [
	"License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
]
```

### Expected outcome

It might be beneficial to have a check that prints a warning if the selected classifier differs from the license

```sh
> poetry run licensecheck
Warning: license classifier "GPLv3+" differs from license "MIT License". Using "GPLv3+"

┌──────────┬────────────────────┬────────────────────┐
│Compatible│Package             │License             │
├──────────┼────────────────────┼────────────────────┤
│True      │add-trailing-comma  │MIT License         │
│True      │appdirs             │MIT License         │
```

### Actual outcome

Right now, the classifier overrides the license, which is confusing if they diverged and licensecheck only reports true/false. In the above example, you might expect all GPL license to be non-compatible because the license is set to MIT

https://github.com/FHPythonUtils/LicenseCheck/blob/42513cf7d30f02f91bdafa3227da2ec81eb07683/licensecheck/packageinfo.py#L195-L198

**Comment by FredHappyface** [comment]
I'd say that's outside the scope of this tool/ requires a surprising amount of refactoring (having taken a good look at this)

The aim being that the licenses of dependencies are checked against the current project. I would say that it's the user's responsibility to ensure that they are identical if duplicating classifiers and license keys 

IIRC the license key is often also a spdx identifier so this change would require in my opinion a disproportionate amount of work to compare licenses at that text stage given this is currently handled later.

Though you are welcome to create a pull request if this is something you'd like to see

**Comment by KyleKing** [comment]
Thanks for taking a look!

I’m all for using the standardized classifiers and it will throw an error if working with a package that hasn’t specified any yet, so I think my edge case isn’t that important

**Comment by FredHappyface** [comment]
It'd probably be worth me using an enumerated type sooner in the logic really but all that function does is try its best to work out what license you are using from a pyproject.toml so shouldn't have any affect on libs
