### ISSUE TITLE
Question: Could you publish a new release with the latest fix(es)

### ISSUE THREAD

**Issue by arunkumarpandian** [FHPythonUtils/LicenseCheck#66]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar questions in the project's issue tracker to avoid duplicates.
- [x] I have searched existing issues to see if this question has been asked before.

## Your Question
@FredHappyface I would appreciate if you could publish a new release with the latest fix(es) - this [one](https://github.com/FHPythonUtils/LicenseCheck/pull/64) in particular. TIA !

**Comment by FredHappyface** [comment]
Thank you for the poke! Should now be available :)

**Comment by arunkumarpandian** [comment]
Thanks @FredHappyface ! Really appreciate it!
