### ISSUE TITLE
Update Matrix for AGPL_3_PLUS

### ISSUE THREAD

**Issue by Sharpz7** [FHPythonUtils/LicenseCheck#67]
Hey,

I am going to need to use AGPLV3with my project, since I am using https://github.com/ultralytics/ultralytics which is under  AGPLV3. This project looks perfect to me, and I would like to contribute.

First, I would want to add https://github.com/FHPythonUtils/LicenseCheck/issues/43. It is GPL compatible which should make it easy to fill in the table. 

Secondly, I think some lines in the matrix are wrong for AGPL:

- AGPL Should be compatible with itself, currently it is not.
- AGPL Should be compatible with Apache V2 (Apache work can be used in AGPL, not the other way round). https://www.apache.org/licenses/GPL-compatibility.html)
- Since AGPL is compatible with GPLV3+, it should also be compatible with ZOTO.

I think separating out Apache V1 and Apache V2 would also be useful, since that is a compatibility problem. But use of Apache V1 is very limited so probably not needed

>"The Free Software Foundation considers all versions of the Apache License to be [incompatible](https://en.wikipedia.org/wiki/License_compatibility) with the previous GPL versions 1 and 2.[[2]](https://en.wikipedia.org/wiki/Apache_License#cite_note-fsflist-2) Furthermore, it considers Apache License versions before 2.0 incompatible with GPLv3"

From https://en.wikipedia.org/wiki/Apache_License

I am happy to add all these changes in a PR. Being able to choose the license in the CLI to use for the project would also be a nice touch I can add. Thanks!

Thanks in advance,
Adam

**Comment by FredHappyface** [comment]
Hi Adam,

Thank you so much for creating the issue, and your interest in the repo/ project :) 

PRs are absolutely welcome! Usually I'd suggest splitting the features over a few PRs but am very happy to review them all together if that's something you're happy with?

Cheers again, 
FredHappyface <3

**Comment by Sharpz7** [comment]
Yeah - just being able to get all this added in one PR would be great for me - the work is quite small in scale so hopefully that works.

I will get on this in the next week or two. Thanks!

**Comment by FredHappyface** [comment]
Awsome stuff, thank you so much :)

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.1.1
