### ISSUE TITLE
Feature: Allow project license to be set as a command line argument

### ISSUE THREAD

**Issue by Roconda** [FHPythonUtils/LicenseCheck#69]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar feature requests in the project's issue tracker
  to avoid duplicates.
- [x] I have searched existing issues to see if this feature has been discussed
  before.

## Feature Details

First of all, thanks for creating licensecheck.

It would be nice to set the project's license by using an command line argument instead of using `pyproject.toml` or `setup.cfg`.

### Is your feature request related to a problem? Please describe

This allows an easier integration for Python projects that aren't packages, which don't require a `pyproject.toml` or `setup.cfg`. It also makes it easier to use within the context of a pipeline and or bash scripts.

### Describe the solution you'd like

Shorthand:

```cli
$ licensecheck -l MIT .
```
Long version:

```cli
$ licensecheck --license MIT .
```

### Describe alternatives you've considered

Currently I've added a `pyproject.toml` to get licensecheck working correctly. Having a `pyproject.toml` for licensecheck only feels a bit like abusing.

**Comment by FredHappyface** [comment]
Added this, just want to get more in before a release

**Comment by Roconda** [comment]
Thank you!

**Comment by FredHappyface** [comment]
Thanks again for this! Finally made the release! https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.1
