### ISSUE TITLE
Feature: add allow/deny list of licences as cmdopt

### ISSUE THREAD

**Issue by Niccolum** [FHPythonUtils/LicenseCheck#7]
As I see - your tool can only find all licences of packages. Is it possible to check according allow/deny lists, to find packages, which I can use or not?

**Comment by FredHappyface** [comment]
Can you provide a bit more info on the sort of thing you mean. If you have time, an example would be great too

Thanks 😊

**Comment by Niccolum** [comment]
One case - I, as developer, change requirements.txt and want to know, that the licences of the libraries in my project do not contradict each other and I don't violate the rules of licenses. For example, that my enterprise project don't use GNU GPL libraries

**Comment by Niccolum** [comment]
One more feature as add-on for this - exclude packages. If package not allowed by allow/deny list, but we can't replace it by another right now, so, we can add it as "excluded package" to replace it later, but our licence checker will show, that all is OK.

**Comment by FredHappyface** [comment]
That's a good idea. The challenge arises from how incompatibilities are determined using a license mapping of sorts based on research that has been conducted on this. 

But yes, using some sort of config or command line argument to disable checking for specific packages is something I can implement fairly easily so I'll likely make that my next task

**Comment by FredHappyface** [comment]
Turns out that implementing this with licenses is easier than expected 

Done in 2021.3 - enjoy :)
