### ISSUE TITLE
Question: Release 2024.1 ?

### ISSUE THREAD

**Issue by tsillus** [FHPythonUtils/LicenseCheck#73]
Not sure if this is the github-way of asking for this, but: could you make a 2024.1 release for the current state? I need the changes in a release for my CI. 

Thanks!

**Comment by FredHappyface** [comment]
Hey thanks for the issue. Yeah absolutely! I'm a bit overdue a realease so I'll sort that asap

**Comment by FredHappyface** [comment]
Sorted :) https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.1
