### ISSUE TITLE
Feature: HTML output format

### ISSUE THREAD

**Issue by ryan-cpi** [FHPythonUtils/LicenseCheck#77]
## Feature Details

Would it be possible to get an HTML output format? pip-licenses support this however, their formatting isn't the best here.

Could this new output include some of the details from the JSON output like name, version, homePage, license and licenseCompat? This would make it a little easier looking back at old reports since licences could change depending on the package version. A simple title of LicenseCheck (version) YYYY/MM/DD would also be quite nice for us.

**Comment by FredHappyface** [comment]
Added in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.2 :) 

Including the following info for each package: Compatible, HomePage, Author, License, and Size (basically it is the markdown output piped through markdown for your convenience) 


eg 



Compatible | Package
-- | --
✔ | Markdown



## Markdown-3.6

HomePage: UNKNOWN
Author: Manfred Stienstra, Yuri Takhteyev
License: BSD LICENSE
Compatible: True
Size: 420069
