### ISSUE TITLE
Feature: support pre-commit hook

### ISSUE THREAD

**Issue by Niccolum** [FHPythonUtils/LicenseCheck#8]
According
https://github.com/FHPythonUtils/LicenseCheck/issues/6
And
https://github.com/FHPythonUtils/LicenseCheck/issues/7

if it possible to realize that - can you add your tool as pre-commit hook? For checking requirements licences after requirements changes. Just exit with zero, if OK and with another code and description, if not.
pre-commit hooks example:
https://github.com/pre-commit/pre-commit-hooks/blob/master/.pre-commit-hooks.yaml

**Comment by FredHappyface** [comment]
Sounds like a great idea! I'll get that looked into

**Comment by FredHappyface** [comment]
fixed in 2021.5
