### ISSUE TITLE
Bug: Using requirements file ignores versions specified inside file

### ISSUE THREAD

**Issue by kyleromero98** [FHPythonUtils/LicenseCheck#83]
## Before You Begin

Before proceeding, please make sure to follow these steps:

- [x] I have checked for similar issues in the project's issue tracker.
- [x] I have searched closed issues to see if a similar problem was reported
  before.

## Issue Details

Bug: Using requirements file ignores versions specified inside file

### Description

Reproduction steps:

EITHER
1 - Activate a virtual environment with some dependency version x.x
2 - Run licensecheck specifying --using on a requirements file in project with versions specified of form <dependency>==<version>, ensure that the same dependency with different version y.y is specified
3 - Observe that licensecheck will use version in the virtual environment instead of version in requirements.txt
OR
1 - Activate a virtual environment without a dependency x inside of requirements file
2 - Run licensecheck specifying --using on a requirements file which contains dependency x with a version of the form <dependency>==<version>, ensure that version is not the latest version of dependency x
3 - Observe that licensecheck uses the latest version scraped from pypi to provide license info

Appears related to the strategy used for loading metadata (using metadata package loads the information from currently running Python environment) or using Pypi if metadata is not found using metadata package. Since this is kind of a large change in strategy, it might be more of a feature than bug.

### Workaround
Existing functionality kind of requires that users are inside of a virtual environment created with their requirements file that they are running licensecheck on in order to get proper version information.

### Expected Behavior

licensecheck should honor the frozen version inside of requirements.txt regardless of Python environment

### Actual Behavior

Described in reproduction steps.

## System Information

- Operating System (OS): Windows
- OS Version: 11

**Comment by FredHappyface** [comment]
Hi thanks for this, the current native resolver is rather primative to say the least so thank you for highlighting this 

The latest commit https://github.com/FHPythonUtils/LicenseCheck/commit/ba70665012b66d0a2497f68fdeec6c3389a45a37 adds a new resolver which should solve this issue. I need to work out how to enable this (my concern is adding too many options to the cli - many I've previously added are already frustrating to me )

Shortly I'll add some tests to confirm this has fixed your issue, I just need a copy of the problematic requirements.txt to test with. Thanks :)

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.3
