### ISSUE TITLE
Bug: comments inside requirements.txt crash licensecheck

### ISSUE THREAD

**Issue by PashaWNN** [FHPythonUtils/LicenseCheck#84]
## Issue Details

If there are comments in requirements file, check fails with `packaging.requirements.InvalidRequirement`

### Description

For example, there is a line in `core/requirements.in`:
```
celery==5.2.7  # run common/celery/strategy.py after updating
```

### Expected Behavior

Check runs ok

### Actual Behavior

```
packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
    celery==5.2.7  # run common/celery/strategy.py after updating
          ~~~~~~~~~^
```

## System Information

- Operating System (OS): MacOS
- OS Version: 14.5
- Project Version (if applicable): 2024.2

**Comment by FredHappyface** [comment]
The latest commit https://github.com/FHPythonUtils/LicenseCheck/commit/ba70665012b66d0a2497f68fdeec6c3389a45a37 adds a new resolver which should solve this issue. I need to work out how to enable this (my concern is adding too many options to the cli - many I've previously added are already frustrating to me )

Shortly I'll add some tests to confirm this has fixed your issue. Thanks :)

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.3
