### ISSUE TITLE
Bug: Unnecessary prompt for license

### ISSUE THREAD

**Issue by alastairtree** [FHPythonUtils/LicenseCheck#85]
When running `python -m licensecheck -u poetry -l "MIT LICENSE"` on a project packaged with poetry I get prompted to "Enter the project license" despite having passed the license on the CLI. 

To show this bug you need a project that does not have a licence in the toml file, e.g. it is commented out:

```
[tool.poetry]
name = "some-thing"
version = "0.1.0"
# license = "Copyright someone"
```

If you add the licence to the pyproject.toml file, the prompt goes away.

Perhaps the issue is that the licence on the cli is getting overwritten in the metadata dictionary by a blank from the config file:
https://github.com/FHPythonUtils/LicenseCheck/blob/master/licensecheck/packageinfo.py#L186

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/LicenseCheck/releases/tag/2024.3
